version: 2
jobs:
  build-ubuntu:
    docker:
      - image: jbaldwindh/liblifthttpbuilder-ubuntu:0.1
      - image: nginx:stable
    steps:
      - checkout
      - run:
          name: build release g++
          command: |
            mkdir build-release-g++
            cd build-release-g++ 
            cmake \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_CXX_COMPILER=g++ .. 
            ninja
      - run:
          name: build release clang++
          command: |
            mkdir build-release-clang++
            cd build-release-clang++ 
            cmake \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ .. 
            ninja
      - run:
          name: test release g++
          command: |
            cd build-release-g++
            ctest -V
      - run:
          name: test release clang++
          command: |
            cd build-release-clang++
            ctest -V
  
  build-fedora:
    docker:
      - image: jbaldwindh/liblifthttpbuilder-fedora:0.1
      - image: nginx:stable
    steps:
      - checkout
      - run:
          name: build release g++
          command: |
            mkdir build-release-g++
            cd build-release-g++ 
            cmake \
                -GNinja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_CXX_COMPILER=g++ .. 
            ninja
      - run:
          name: build release clang++
          command: |
            mkdir build-release-clang++
            cd build-release-clang++ 
            cmake \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ .. 
            ninja
      - run:
          name: test release g++
          command: |
            cd build-release-g++
            ctest -V
      - run:
          name: test release clang++
          command: |
            cd build-release-clang++
            ctest -V

workflows:
  version: 2
  build-test:
    jobs:
      - build-ubuntu
      - build-fedora
